name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        redis-version:
          - "4.0"
          - 4.1
          - 4.2
          - 4.3
          - 4.4
          - 4.5
          - 4.6
          - 4.7
          - 4.8
          - latest
        ruby-version:
          - 2.6
          - 2.7
          - "3.0"
          - 3.1
          - 3.2
          - 3.3
          - 3.4
          - head
        rack-version:
          - 1
          - 2
          - 3
        exclude:
          - { ruby-version: 2.6, rack-version: 3 }
    env:
      REDIS_VERSION: "${{ matrix.redis-version }}"
      RACK_VERSION: "${{ matrix.rack-version }}"

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
      - run: sudo apt-get install redis-server
      - run: bundle exec rake

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - run: bundle exec rubocop
